# Use for HTML -- 
# link: https://www.dailysmarty.com/posts/steps-for-deploying-a-static-html-site-with-docker-and-nginx
FROM nginx:alpine
COPY app.html /usr/share/nginx/html/index.html


# Use for JavaScript -- {

# FROM node:alpine
# COPY ./ hello_docker1

# open folder path and go inside
# WORKDIR /hello_docker1

# Run by command / CMD
# CMD node app.html

#  }